### ISSUE TITLE
Normalize software sharing between closed-source and Open Source

### ISSUE THREAD

**Issue by dcramer** [chadwhitacre/howtoshare.software#1] opened 2024-02-08 18:26 UTC
## Update

_from @chadwhitacre_

### The Story So Far

A year and change ago, Sentry [bought](https://blog.sentry.io/bringing-codecov-into-the-sentry-family-where-code-coverage-meets-application-monitoring/) Codecov. Eight months ago, we published it under BUSL-1.1. Our headline said "[Codecov is now Open Source](https://about.codecov.io/blog/codecov-is-now-open-source/)," which set off [a vigorous discussion](https://news.ycombinator.com/item?id=36971490) about the meaning of the term Open Source, out of which emerged [this proposal](https://twitter.com/adamhjk/status/1687113805237714944) from @adamhjk: 

> I think the way forward here is to make what I suspect is a loose confederation of folks using non-compete licenses to actually get together and draft their own set of values. To then brand that. And stand behind it proudly.

We started a repo at [getsentry/loose-confederation](https://github.com/getsentry/loose-confederation) with discussions about [overall goals](https://github.com/getsentry/fsl.software/issues/36) as well as [brand naming](https://github.com/getsentry/fsl.software/issues/2). We also started writing a new license, [FSL](https://fsl.software/), which we [shipped](https://blog.sentry.io/introducing-the-functional-source-license-freedom-without-free-riding/) five months ago. The loose-confederation repo has been downscoped to focus on that.

Meanwhile, Software Commons [emerged](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1976628352) as a strong brand for _something_, but not for what we originally set out to do based on Adam's suggestion. Software Commons is now evolving into [an attempt to solve the sustainability crisis in Open Source](https://openpath.chadwhitacre.com/2024/the-case-for-a-new-institution/); you can [join that conversation over here](https://github.com/softwarecommons/softwarecommons.com/issues/4). The present ticket was brought from what is now the fsl.software repo to this here new repo, which is for a website called [howtoshare.software](https://howtoshare.software/).

### Our Purpose Here

From @dcramer on https://github.com/getsentry/fsl.software/issues/2:

> The intent here is to normalize a category of software which provides more freedom than closed source, and more freedom than typical source-available software. It should not diminish the value of FOSS (or OSI's definition of "Open Source"), but should also not be overly confusing to end-users, and not include prejudice.

I've updated the issue title based on this intent: "Normalize software sharing between closed-source and Open Source." The site currently live at [howtoshare.software](https://howtoshare.software/) pursues this intent by defining _levels_ of source availability. I propose that we use this issue to see if we can converge on details under this general approach.

----

## Original

_from @dcramer_

Let's educate the broader open source community on where these style of licenses make sense. There's far too many conversations where Open Source is one giant bucket of things, but thats not how the world actually operates.

For example, if you're building a library, FSL almost certainly should not be used (and frankly, non-compete in general should be avoided). Obviously thats our opinion, but given this entire thing is our opinion thats ok, and it doesnt need stated that the team has a lot of historical domain experience in mainstream open source. I would go so far as to say we should suggest libraries be put under a fully permissive license, but we should run the exercise of the core licenses and which models they might work best in (permissive, copyleft, non-compete, and maybe even closed source/proprietary?).

We should also not exclusively tie it to the _type_ of code, but the organizational and/or business model in general.

**Comment by chadwhitacre** [comment] 2024-03-07 16:50
I've done a bunch of shenanigans to hopefully get conversations in the right place. This issue now lives in the repo for [howtoshare.software](https://howtoshare.software/). I've written a long update in the issue description for context if anyone is lost.

**Comment by chadwhitacre** [comment] 2024-03-07 18:12
Picking up from @mattisg at https://github.com/getsentry/fsl.software/issues/2#issuecomment-1982328368:

> finding sustainable business models in open-source for initial vendors through increased friction to reuse

This narrative framing is not adequate to encompass the full range of relevant observable phenomena.

Yes, HashiCorp _did_ betray the community when they relicensed Terraform from an Open Source project to a BUSL-1.1-licensed product. It _was_ a rug pull. The community's response in creating a viable fork, OpenTofu, is a shining example of the power of Open Source licensing to forestall [enclosure of software as an information good](https://openpath.chadwhitacre.com/2024/the-case-for-a-new-institution/#enclosure-of-information). This is the system "working as intended," the community routing around the misbehavior of HashiCorp when they "increased friction to reuse."

Consider movement in the other direction, though. Codecov was closed-source when Sentry [bought](https://blog.sentry.io/bringing-codecov-into-the-sentry-family-where-code-coverage-meets-application-monitoring/) it. Because of [DOSP](https://opensource.org/dosp) licensing under BSL/FSL, we were able to publish the source code, creating real benefits for users without jeopardizing our capacity to continue producing it. You used to have to pay to self-host Codecov. [Now you don't](https://github.com/codecov/self-hosted). The same is true for [AnswerOverflow](https://github.com/AnswerOverflow/AnswerOverflow), [GitButler](https://github.com/gitbutlerapp/gitbutler), and [CodeCrafters](https://github.com/codecrafters-io/frontend), which have all gone from closed-source to source available in the five months since we published FSL. In these cases, the companies in question have decreased "friction to reuse."

As @dcramer expressed in the quote at the top of this issue:

> The intent here is to normalize a category of software which provides more freedom than closed source, and more freedom than typical source-available software. It should not diminish the value of FOSS (or OSI's definition of "Open Source"), but should also not be overly confusing to end-users, and not include prejudice.

This is behind how I've distinguished _levels_ of source availability in the first draft of [howtoshare.software](https://howtoshare.software/).

> open-source software that has democratic governance

I think differences in governance are worth having in mind when we look at software sharing practices. I almost wonder if we don't need to update our model of the "freedoms" of software. On the one hand [the existing freedoms are poorly structured](https://twitter.com/chadwhitacre_/status/1755357534422958570), on the other hand it may be worthwhile to directly incorporate "freedom to participate in governance." 🤔

<img width="979" alt="how to share" src="https://github.com/softwarecommons/howtoshare.software/assets/134455/24f63705-624b-46f1-8f22-3e60906d9ced">

**Comment by chadwhitacre** [comment] 2024-03-07 18:12
Bringing this over from https://github.com/getsentry/fsl.software/issues/2#issuecomment-1982328368 as well:

> References:
> 
> • OpenFuture's [Paradox of Open](https://paradox.openfuture.eu/policies/) ([summary](https://maly.io/@MattiSG/111497868924056051))
> • Joint Statement on the [Creation of a European Initiative for Digital Commons](https://www.diplomatie.gouv.fr/en/french-foreign-policy/digital-diplomacy/news/article/joint-statement-by-the-ministry-for-europe-and-foreign-affairs-and-the-state)
> • Next Generation Internet: [Forum 2023](https://ngiforum2023.eu) and [Commons call](https://commons.ngi.eu)
> • Open Knowledge Foundation’s [Tensions in Commons](https://tensionsincommons.net)
> • PublicSpaces [statement](https://publicspaces.net/2023/10/13/public-digital-infrastructure-fund-op-weg-naar-europese-steun-voor-publieke-digitale-infrastructuren/) and [Building Digital Commons](https://video.publicspaces.net/w/gwLJu27zb8a4r1dRi7wdU1?start=13m10s) conference

**Comment by chadwhitacre** [comment] 2024-03-08 18:19
In https://github.com/softwarecommons/howtoshare.software/compare/a67fef2156e24cdb3e4505e005015ea259d2c15c...844028e9d7145f4e1cb65dc83bde79cf11bfa188 I've renamed what was Open Product to Fair Source, and added back a modified Open Product as a fifth level. Why?

### 1. "Open" = Communal, Not Corporate

> differences in governance

Picking up from our previous thread ([one](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1828680525), [two](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1936504225), [three](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1936095122)), and reframing in terms of governance: any application of "open" to efforts with corporate instead of communal governance—and yes, we need a fuller discussion of those concepts—will be seen as open-washing (see also: [recent OpenAI disclosures](https://twitter.com/Scobleizer/status/1765266609374171523)).

### 2. "Fair" Has the Most Common Ground So Far

I've seen @ssddanbrown ([ref.](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1795905161)) and @mswilson ([ref.](https://github.com/getsentry/fsl.software/issues/2#issuecomment-1981529753)) both indicate that Fair Source would be an acceptable term to describe Sentry, Codecov, GitButler, etc. I feel like the vibe in our internal Sentry chat has been more or less okay with "Fair" as a descriptor as well. I think it may be the least bad option, a _fair_ compromise between interested parties. ;-)

### 3. "Fair" Has the Most External Momentum So Far

Looking at existing efforts, [Fair Source License](https://fair.io/) can fit: it's a specific instance of the Fair Source pattern. Maybe there's a slight risk of muddying the waters, but I don't think it's insurmountable. Otoh, [Fair Code](https://faircode.io/) is basically saying what I think we want to say about Fair Source. That's also fine, imo; they can be synonyms. The story, then, is basically:

> Fair Source encompasses a range of source available software sharing options for companies that want to grant some real freedoms while also protecting their business interests. Also sometimes called "Fair Code,"  the Fair Source License is one specific license in this category, which also includes BUSL, FSL, etc.

### 4. "Open Products" = Communal Fair Source(!)

[Revisiting](https://github.com/chadwhitacre/openpath/issues/10) "[Open Products](https://gratipay.news/open-products-25824a325fea)," I want to reserve that term for software products with Fair Source licensing **_and communal governance_**. This is where the real innovation is, in my view. Firms are demonstrably better at building consumer-grade software products, so let's take the firm-friendly licensing of Fair Source, and combine it with communally governed firms (i.e., cooperatives). This creates a new economic relation, wherein individuals have [real control](https://gratipay.news/sharing-our-take-what-you-want-story-911dad62ac32) over their participation in the economic benefits of a successful product.

<img width="941" alt="update" src="https://github.com/softwarecommons/howtoshare.software/assets/134455/143ca3cf-99ad-4aae-989e-c65f7bdffe89">

**Comment by MattiSG** [comment] 2024-03-10 09:31
> > finding sustainable business models in open-source for initial vendors through increased friction to reuse
> 
> This narrative framing is not adequate to encompass the full range of relevant observable phenomena.
> […]
> have all gone from closed-source to source available in the five months since we published FSL. In these cases, the companies in question have decreased "friction to reuse."

Just to clarify: I meant “increased friction to reuse” _as compared to open-source licenses_, not as compared to some existing state of affairs. FSL _does_ add more friction to reuse than MIT. I don't think it's bad in the current context, I am acutely aware of the difficulty of getting an income from developing open-source software and I am also led to think that, lacking a government-provided solution, we need to find some middle ground.

**Comment by chadwhitacre** [comment] 2024-06-11 16:09
Closing in favor of https://github.com/fairsource/fair.io/issues/14.

**Closed by chadwhitacre** 2024-06-11 16:09 UTC
